// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWWbT6Svb40xrdI2ZIkHk5i_Qw5A-KUKQ',
    appId: '1:1078256956153:web:936290edaf93c4e970e828',
    messagingSenderId: '1078256956153',
    projectId: 'elewa-e3f2a',
    authDomain: 'elewa-e3f2a.firebaseapp.com',
    storageBucket: 'elewa-e3f2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAesxHj9t5A_WoB2WQva045-aDsELmVgD0',
    appId: '1:1078256956153:android:a101c90e953b11a070e828',
    messagingSenderId: '1078256956153',
    projectId: 'elewa-e3f2a',
    storageBucket: 'elewa-e3f2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWCpLoMDxglkCaUJBKnJJ0q2yVt9efo7U',
    appId: '1:1078256956153:ios:c490a97aa221f55c70e828',
    messagingSenderId: '1078256956153',
    projectId: 'elewa-e3f2a',
    storageBucket: 'elewa-e3f2a.appspot.com',
    iosBundleId: 'com.example.elewaTest',
  );
}
